# Generated by Django 4.1.2 on 2022-10-26 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_app', '0004_userprofile_is_staff_userprofile_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_superuser',
        ),
    ]
